model_type: llm
base_model: meta-llama/Llama-2-7b-hf

#quantization:
#  bits: 4

adapter:
  type: lora

prompt:
  template: |
    ### Instruction:
    {instruction}

    ### Response:

input_features:
  - name: prompt
    type: text

output_features:
  - name: response
    type: text

trainer:
  type: finetune
  learning_rate: auto
  learning_rate_scaling: sqrt
  batch_size: auto
  gradient_accumulation_steps: 16
  epochs: 3
  learning_rate_scheduler:
    warmup_fraction: 0.01
  optimizer:
    type: adamw
  use_mixed_precision: true
  compile: true

preprocessing:
  sample_ratio: 0.1